correct bitbucket token format

diff --git a/.github/workflows/run-cypress-tests.yml b/.github/workflows/run-cypress-tests.yml
--- a/.github/workflows/run-cypress-tests.yml
+++ b/.github/workflows/run-cypress-tests.yml
@@ -55,11 +55,29 @@ jobs:
         env:
           BITBUCKET_TOKEN: ${{ secrets.BITBUCKET_TOKEN }}
         run: |
+          echo "Debug: Start committing report to Bitbucket"
+
+          # Set Git user details
           git config --global user.name "GitHub Actions"
           git config --global user.email "actions@github.com"
-          git clone --branch reports https://x-token-auth:$BITBUCKET_TOKEN@bitbucket.org/thabit1/prapplicationtesting.git reports || git clone https://x-token-auth:$BITBUCKET_TOKEN@bitbucket.org/thabit1/prapplicationtesting.git reports
+          git config user.email "ub5fjhx5cudmtxol9d4y1c8rjqr71t@bots.bitbucket.org"
+
+          echo "Debug: Cloning repository"
+          git clone https://x-token-auth:${BITBUCKET_TOKEN}@bitbucket.org/thabit1/prapplicationtesting.git reports || echo "Cloning failed"
+
+          echo "Debug: Copying reports"
           cp -r cypress/reports/* reports/
+
           cd reports
+
+          echo "Debug: Status of git repository"
+          git status
+
+          echo "Debug: Adding files"
           git add .
+
+          echo "Debug: Committing changes"
           git commit -m "Update Cypress HTML report" || echo "No changes to commit"
-          git push origin reports
+
+          echo "Debug: Pushing changes"
+          git push origin main || echo "Push failed"
